#!/usr/bin/env bash

#tmux `cat tmux/tmux-monitor.conf|sed -e 's/$/ \\; /'|tr -d '\n'`
#tmux new-session "tmux source-file /home/gousiosg/cluster/tmux/tmux-monitor.conf"

tmux new-session \; split-window -v \; split-window -h \; select-pane -t 0 \; split-window -h \; select-pane -L \;  send-keys 'ssh bdp2' C-m \; send-keys 'nmon' C-m \; send-keys 'c' \; select-pane -R \; send-keys 'ssh bdp3' C-m \; send-keys 'nmon' C-m \; send-keys 'c' \; select-pane -D \; select-pane -L \; send-keys 'ssh bdp4' C-m \; send-keys 'nmon' C-m \; send-keys 'c' \; select-pane -R \; send-keys 'ssh bdp5' C-m \; send-keys 'nmon' C-m \; send-keys 'c' \;
